* Todo List

** TODO Make handlers
*** handle-ping
    Nothing too special here.
*** handle-confirm
    Very straightforward, respond CONFIRMED if the transient is there.
*** handle-commit
    Very straightforward as well, simply update the =state= atom and
    then respond. Will send =RETRY= if the state object seems to be missing.
*** handle-elect
    Need to figure out how the leader piece will interact with node
    and define that more clearly before I go forward with this handler.
*** handle-term
    This will also need some more thought.

** TODO Clear transient-state after a timeout

** TODO Consider another more flexible handler methodology

** TODO Create Worker communication system

*** Leader

    Leader worker creates a leader connector (for heartbeat) and a
    state publishing socket. 

*** State
    
    State worker needs to be re-run each and every time there is a
    leader change or term change (same as leader change)

*** Control

    This worker is the longer running worker and will /not/ be
    affected by any changes in state.
    
    The control worker also will take control of negotiating the
    changes in the current leader.

** DONE Figure out leader "worker thread" calling and bindings.
   CLOSED: [2014-07-17 Thu 17:32]
   - Note taken on [2014-07-17 Thu 17:32] \\
     Using a better more distinct worker layout

* Potential issues

** control-worker may receive requests while in the middle of a dialog
   There is the potential for a dialog to be interrupted while talking
   to a leader. If this occurs while replying the loop would be
   blocked. May need to set a timeout somewhere.. (maybe send-str?)

